### ISSUE TITLE
Where is ulid.js

### ISSUE THREAD

**Issue by andcuevas** [ulid/javascript#62]
In the documentation says:

Browser

<script src="/path/to/ulid.js"></script>
<script>
    ULID.ulid()
</script>

where is this ulid.js file?
How can I generate this file using the project files?

**Comment by tchapi** [comment]
Up !

**Comment by rogaldh** [comment]
https://github.com/ulid/javascript/blob/master/package.json#L5

**Comment by alizain** [comment]
Made the docs clearer on this
