### ISSUE TITLE
Support for RFC 4648 base32?

### ISSUE THREAD

**Issue by gengel** [ulid/javascript#63]
It would be convenient for me personally if this library supported a variant of ulid that was encoded in RFC 4648 base32 instead of Crockford's base32.  (Obviously, this would violate the ulid spec.)

**Comment by RobThree** [comment]
> Obviously, this would violate the ulid spec.

Which would only confuse matters. I'd certainly advice against different ULID implementations using different base32 algorithms. That doesn't mean that you can't fork this (or any) implementation and build your own; I'd just advice to come up with another name (I'd suggest NULID for "Not a ULID", but that would, again, be confusing with the [.Net implementation](https://github.com/RobThree/NUlid) 😜 ). So maybe MULID for "My ULID" or whatever creative name you can come up with on your own and use that for your implementation. That would keep all **ULID's** compatible.

**Comment by alizain** [comment]
Agreed with @RobThree
