### ISSUE TITLE
Is there a way to get the timestamp from a given ULID?

### ISSUE THREAD

**Issue by dashmug** [ulid/javascript#65]
Use case: 

If I store the ULID in the DB and I can retrieve timestamp information from the ULID, I won't need to store a separate timestamp column anymore.

**Comment by ryanatkn** [comment]
See [decodeTime](https://github.com/ulid/javascript/blob/master/lib/index.ts#L97). Looks like it's not documented in the README.

**Comment by alizain** [comment]
@dashmug `decodeTime` will work

**Comment by alizain** [comment]
Closing the issue, feel free to re-open if you need to
