### ISSUE TITLE
Decoding ULID string into bytes

### ISSUE THREAD

**Issue by ErkoKnoll** [ulid/javascript#96]
Hi,

I've been trying to decode ULID into bytes for more efficient storage. I didn't notice there is a way to retrieve the raw bytes from the library itself so I tried using Crockford's base32 encoding to do it manually, as the docs say it uses this specific encoding. However when using [base32-encode](https://www.npmjs.com/package/base32-encode) and [base32-decode](https://www.npmjs.com/package/base32-decode) sometimes there seems to be precision errors, last encoded character won't match the original ULID. Docs do mention that there is 2 bit difference between Crockford's encoding and ULID's length (130 bit vs 128), which I suspect may lead to encoding error. My question is how to do it properly?

Example:
```
import { ulid } from 'ulid';
import b32decode from 'base32-decode';
import b32encode from 'base32-encode';

const uid = ulid();
console.log('UID', uid);

const decoded = b32decode(uid, 'Crockford');
console.log('DECODED', decoded);

const encoded = b32encode(decoded, 'Crockford');
console.log('ENCODED', encoded);
```

Output:
UID 01FZD39998855SS2YG4XP4T14**P**
DECODED ArrayBuffer {
  [Uint8Contents]: <00 5f f6 8d 29 4a 10 52 e7 22 f4 09 db 13 41 25>,
  byteLength: 16
}
ENCODED 01FZD39998855SS2YG4XP4T14**M**

**Comment by samal-rasmussen** [comment]
`01FZD39998855SS2YG4XP4T14P` is a valid base32 encoded string and a base32 string should round trip between `b32decode` and `b32encode` to the same value. If it doesn't then there's a bug there. It has nothing to do with ulid.

I found a different encoding package `crockford-base32` that isn't bugged:
```
import b32decode from 'base32-decode';
import b32encode from 'base32-encode';
import {CrockfordBase32} from 'crockford-base32';

const uid = '01FZD39998855SS2YG4XP4T14P';

const buffer = CrockfordBase32.decode(uid)
console.log('decoded', bufferToString(buffer))
const res = CrockfordBase32.encode(buffer);
console.log('encoded', res)

const decoded = b32decode(uid, 'Crockford');
console.log('DECODED', bufferToString(new Uint8Array(decoded)));
const encoded = b32encode(decoded, 'Crockford');
console.log('ENCODED', encoded);

function bufferToString(buffer) {
  let nums = [];
  for (let i = 0 ; i < buffer.length ; i++) {
    nums.push((buffer[i] + '').padStart(3, ' '))
  }
  return '[ ' + nums.join(',') + ' ]'
}
```

Result:
```
decoded [   1,127,218, 52,165, 40, 65, 75,156,139,208, 39,108, 77,  4,150 ]
encoded 01FZD39998855SS2YG4XP4T14P
DECODED [   0, 95,246,141, 41, 74, 16, 82,231, 34,244,  9,219, 19, 65, 37 ]
ENCODED 01FZD39998855SS2YG4XP4T14M
```

Run it on replit:
https://replit.com/@samalrasmussen/SeagreenPriceyDeletion

**Comment by ErkoKnoll** [comment]
Thanks @samal-rasmussen!
